import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useContext, useRef } from 'react'
import { UserContext } from './hooks/usercontext'
import Router, { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();
  const {value, setValue} = useContext(UserContext);
  const inputRef = useRef<any>(null);

  function setNew(){
    let newVal = value;
    if (inputRef.current != null){
      newVal = inputRef.current.value

    }
    localStorage.setItem("name", newVal);
    setValue(newVal);
  }
  const handleLogOut = () => {
    localStorage.removeItem("name");
    window.location.reload();
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <input
        ref = {inputRef}
        type = "text"/>
        <button onClick={setNew}>Login</button>

      </div>
      <main>
        <div>
          {value ? <div>Logged in as {value}<button onClick={handleLogOut}>LogOut </button></div> : null }
        </div>
      </main>
    </>
  )
}
