import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useContext, useRef } from 'react'
import { UserContext } from './hooks/usercontext'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {value, setValue} = useContext(UserContext);
  const inputRef = useRef<any>(null);

  function setNew(){
    let newVal = value;
    if (inputRef.current != null){
      newVal = inputRef.current.value

    }
    setValue(newVal);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <input
        ref = {inputRef}
        type = "text"/>
        <button onClick={setNew}>set new contextValue</button>

      </div>
      <main>
        {value}
      </main>
    </>
  )
}
